apiVersion: v1
kind: ConfigMap
metadata:
  name: landcover-config
  namespace: landcover
data:
  APP_ENV: prod
  LOG_LEVEL: INFO
  ADMIN_USER: admin
  S3_ENDPOINT: http://minio:9000
  S3_BUCKET: landcover
  MLFLOW_TRACKING_URI: http://mlflow:5000
  MODEL_NAME: snunet_cbam
  MODEL_STAGE: Production
  INFERENCE_URL: http://inference:8001
  TRAINING_URL: http://training:8002
  REDIS_URL: redis://redis:6379/0
