resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - inference-deployment.yaml
  - inference-service.yaml
  - training-deployment.yaml
  - training-service.yaml
  - worker-deployment.yaml
  - postgres.yaml
  - minio.yaml
  - redis.yaml
  - mlflow.yaml
  - prometheus.yaml
  - grafana.yaml
  - hpa-gateway.yaml
  - hpa-worker.yaml
